### PR TITLE
Py3.7

### PR DESCRIPTION
**Pull request by ale-rt**
Mock is in the unittest library since Python 3.3
httpbin.org is now on https
solr_dates should be hashable
Test more Python versions

### CODE REVIEW

**Comment by ale-rt** [comment]
A release if possible would be nice, I am using this branch in production since a month

**Comment by delijati** [comment]
Hi ale-rt, i will take look into that did not touch that library for quite a while.

**Comment by delijati** [comment]
@ale-rt can you add yourself to the CONTRIBUTORS and a line to CHANGES then all should be good to go

**Comment by ale-rt** [comment]
Done! I also removed from the travis build matrix Python 2.6 and Python 3.3.
They are unsupported since years and they were not listed in setup.py as supported versions.

**Comment by delijati** [comment]
released 0.13.0

**Comment by ale-rt** [comment]
Thanks!

**Pull request merged**
