### PR TITLE
SSL connection requires byte strings, not Unicode literals

### PR DESCRIPTION
**Pull request by quinot**
Fix type of JSON string literals for administrative commands (commit,
optimize, rollback).

### CODE REVIEW

**Comment by delijati** [comment]
All tests are running with and without the ``b`` so no real need to change this.

**Comment by quinot** [comment]
Well, that's not what I've been seeing. Are you testing with Python 2.7?

```Exception raised processing 7830-007: buf must be a byte string
Traceback (most recent call last):
[...]
  File "/reportd/gnos-3.0w-20161122-x86_64-linux-bin/lib/site-python/scorched/connection.py", line 400, in commit
    softCommit=softCommit))
  File "/reportd/gnos-3.0w-20161122-x86_64-linux-bin/lib/site-python/scorched/connection.py", line 122, in update
    response = self.request('POST', url, data=body, headers=headers)
  File "/reportd/gnos-3.0w-20161122-x86_64-linux-bin/lib/site-python/scorched/connection.py", line 71, in request
    return self.http_connection.request(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1039, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1073, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1035, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 883, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 855, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 208, in sendall
    return self.connection.sendall(data)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 969, in sendall
    raise TypeError("buf must be a byte string")
TypeError: buf must be a byte string
```

**Comment by quinot** [comment]
Hello, can you give a status update on this pull request?

**Comment by delijati** [comment]
As mentioned above this seams unrelated with scorched. Here some google results:

- https://github.com/travis-ci/travis-ci/issues/3003
- https://github.com/orcasgit/python-fitbit/issues/79
- http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package/29099439#29099439
- And bytes in py2 is just a alias for str http://stackoverflow.com/questions/5901706/the-bytes-type-in-python-2-7-and-pep-358

**Pull request closed without merging**
