### PR TITLE
Issue 41 highlighting

### PR DESCRIPTION
**Pull request by mlissner**
This should fix issue #41 by mirroring the `solr_highlighting` attribute that was available in Sunburnt. I had to make a small tweak to the `from_json` method so that it would know the correct unique key, but otherwise I think this is a fairly straightforward fix. 

Also includes tests, and I bumped the version and change log, in hopes of making your job easier.

Please let me know what you think.

### CODE REVIEW

**Comment by mlissner** [comment]
This ended up being a slightly bigger PR than I had hoped for. I just pushed some more commits that do a couple of additional things:

1. I discovered a bug in #38 that made it so that multi-value dates were not returned properly. Fixed.
2. The grouping was significantly under developed, so this fleshes it out significantly, including grouping adding `solr_highlights` attributes to the groups.

The big picture here is that users can use highlighting or groups or both or neither, and the code needs to support all of that. 

It should be *a lot* better now, with support for all of the above. I've also added a lot of tests, so I look forward to your review and hopefully a new release as soon as possible.

Thank you!

**Comment by delijati** [comment]
@lujh any objections? Looks good to me!

**Comment by lujh** [comment]
I just merged the PR. @delijati I would raise the version to 0.11.0 ok?

**Comment by mlissner** [comment]
@lujh, it looks like you got a 👍 from @delijati on the bump to 0.11.0. Do you know when you'll be able to release that?

**Pull request merged**
